### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by bheadwhite** [jaredjbarnes/react-motion-ux#3]
![image](https://user-images.githubusercontent.com/26074150/109396436-ce158b00-78ee-11eb-885d-587f58681a01.png)

getting the above stack error when. trying to load the bundle. ive been playing with plugins and trying to figure out webpack settings to configure a polyfill or something. the way i understand it is that after compiling it is still in commonjs module exports and i needs to be converted to ES module..?

Still playing with it. any feedback appreciated!

**Comment by jaredjbarnes** [comment]
This is now closed, it has been fixed sense v0.4.27.
